name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - run: python -m pip install --upgrade pip
      - run: pip install -r requirements.txt
      - run: pip install pre-commit

      - run: pre-commit run --all-files
      - run: bandit -c .bandit -r src/vaulty
      - run: coverage run -m pytest
      - run: coverage report -m
      - run: radon cc -s -n C src/vaulty
