name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install pre-commit bandit pytest coverage radon

      - name: Run pre-commit (lint/format)
        run: |
          pre-commit run --all-files || true

      - name: Static security scan with Bandit
        run: |
          bandit -c .bandit -r src/vaulty --exit-zero

      - name: Run tests with coverage
        run: |
          coverage run -m pytest || true
          coverage report -m || true

      - name: Check code complexity with Radon
        run: |
          radon cc -s -n C src/vaulty || true
